### PR TITLE
[#29] homebrew formulae

### PR DESCRIPTION
**Pull request by pavertomato**
this PR contains:

- homebrew formulae
- readme update

### CODE REVIEW

**Comment by dzelemba** [comment]
Can we publish the rb file as part of the release? That way someone can install previous versions without code modifications and we don't have to update the rb file on every release.

**Comment by pavertomato** [comment]
> Can we publish the rb file as part of the release? That way someone can install previous versions without code modifications and we don't have to update the rb file on every release.

yep, but we'll have to store template file with placeholders in repo anyway

**Comment by dzelemba** [comment]
Sure storing a template in the repo is fine.

**Comment by pavertomato** [comment]
> Sure storing a template in the repo is fine.

done

**Pull request merged**
