### PR TITLE
[#38] additional positioning tags

### PR DESCRIPTION
**Pull request by pavertomato**
if size of original image is not available those tags won't be added

### CODE REVIEW

**Review by dzelemba — COMMENTED** [review]
Thanks for adding this! Could we add unit tests & integration tests to cover this new logic?

**Comment by pavertomato** [comment]
> Thanks for adding this! Could we add unit tests & integration tests to cover this new logic?

sure, as soon as user will report that feature works fine

**Comment by danielbeaudreau** [comment]
Can this be merged?

**Comment by pavertomato** [comment]
> Can this be merged?

yep, but still no response from user who requested this feature

**Comment by danielbeaudreau** [comment]
Looked at the bug, I guess we got some new feedback

**Comment by danielbeaudreau** [comment]
This is fairly out date by now, so closing this PR.

**Pull request closed without merging**
