### PR TITLE
Refactor for Pruning update

### PR DESCRIPTION
**Pull request by Philbrick**
Move variables into WsiToDcm to simplify/clean class methods.
Add basic max/min for int command line parameters.
Remove cWrapper.h cWrapper.cpp

### CODE REVIEW

**Comment by danielbeaudreau** [comment]
Looks good, just wondering why we need the c wrapper still?

**Comment by Philbrick** [comment]
I'm not sure we do need the C interface. I removed it, then had second thoughts, that it must have been created for a reason, maybe interfacing e.g., JNI?  I thought if I could easily bring it forward I should.

**Pull request merged**
