### PR TITLE
List dependencies for binary install

### PR DESCRIPTION
**Pull request by fedorov**
The binary install instructions did not work for me, and I had to install couple more packages listed in this PR. 

This was using standard `debian-10-buster-v20201112` image in GCP.

### CODE REVIEW

**Comment by fedorov** [comment]
@googlebot I signed it!

**Review by pavertomato — APPROVED** [review]

**Comment by pavertomato** [comment]
https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/pull/43
also i've created PR to fix failed builds in cloud build, could you please pull it to your branch as it will be merged?

**Comment by fedorov** [comment]
@pavertomato how about you merge #43, and then I will rebase this PR to the updated `develop` branch?

**Comment by pavertomato** [comment]
> @pavertomato how about you merge #43, and then I will rebase this PR to the updated `develop` branch?

this is exactly what i meant(does not matter pull or rebase), but i can't merge #43 by myself, we have to wait for @dzelemba

**Comment by danielbeaudreau** [comment]
I merged #43. Thanks Egor

**Comment by fedorov** [comment]
@googlebot I consent

**Comment by danielbeaudreau** [comment]
The build is failing because https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/pull/43 isn't in this branch I think. But since this is a text only change, merging should be fine.

**Pull request merged**
