### PR TITLE
Fix minor mistakes that was found by PVS-Studio

### PR DESCRIPTION
**Pull request by SibgatullinAP**
This PR contains fixes for some mistakes that was found by PVS Studio (static code analyzer https://pvs-studio.com/en/). 
Although there was more mistakes that was found by PVS, i've decided to fix only obvious ones. If you are interested in other mistakes i can send you a full report from PVS.

### CODE REVIEW

**Comment by Philbrick** [comment]
Thank-you for your contribution. Please complete the  Contributor License Agreement (CLA).  After you do this, we should able to merge your changes. Yes, if possible please share the additional PVS findings in a comment.

**Comment by SibgatullinAP** [comment]
Hi! Sources for HTML report can be found here https://github.com/SibgatullinAP/sc_computational_models/tree/main/hw_1/1_5b/PVS_report. Just copy folder and open index.html in your browser.  If you want just to take a look at the PVS-report you can  open pdf below:
[jbubc-67hd1.pdf](https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/files/10174654/jbubc-67hd1.pdf)

**Review by Philbrick — APPROVED** [review]

**Pull request merged**
