### PR TITLE
Crop downsamples

### PR DESCRIPTION
**Pull request by Philbrick**
Adds cropping parameter to cropping imaging to  force downsample images to be multiples of each other.
Adds 4 end to end tests

### CODE REVIEW

**Comment by danielbeaudreau** [comment]
please rebase to fix merge conflict

**Comment by Philbrick** [comment]
I'm going to break this change up into parts to simplify the review.  I wil close this change when we get it integrated.

**Comment by danielbeaudreau** [comment]
Cool, thanks!

**Comment by Philbrick** [comment]
Closing pull.  Redundant and outdated.

**Pull request closed without merging**
